# ownCloud with MariaDB/MySQL
# Access via "http://localhost:8080" (or "http://$(docker-machine ip):8080" if using docker-machine)
# During initial ownCloud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: root
# Database password: example
# Database name: pick any name
# Database host: replace "localhost" with "mysql"

version: '2'

services:

  client:
    #image: crisisbox/client
    build: client
    depends_on:
      - owncloud

  server:
    #image: crisisbox/server
    build: server
    privileged: true
    depends_on:
      - owncloud

  owncloud:
    image: owncloud
    volumes:
      - ./docker/owncloud-data:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mariadb
    volumes:
      - ./docker/db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx-dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - owncloud
      - server
      - client
